#!/usr/bin/env python3
"""
Sample Dog Park Data Generator for HundeparkFinder.de

This script creates a sample dataset of dog parks across major German cities
to demonstrate the structure and content for the website.
"""

import os
import csv
import json
from datetime import datetime

# Configuration
OUTPUT_DIR = "dog_park_data"
CSV_FILENAME = "hundewiesen_germany.csv"

# Ensure output directory exists
if not os.path.exists(OUTPUT_DIR):
    os.makedirs(OUTPUT_DIR)
    print(f"Created output directory: {OUTPUT_DIR}")

# CSV headers
CSV_HEADERS = [
    "id",
    "name",
    "address",
    "postal_code",
    "city",
    "state",
    "latitude",
    "longitude",
    "google_maps_url",
    "phone",
    "opening_hours",
    "website",
    "description",
    "is_fenced",
    "has_water",
    "has_agility",
    "has_seating",
    "has_waste_bins",
    "has_lighting",
    "has_parking",
    "photos",
    "rating",
    "reviews",
    "size",
    "last_updated",
    "data_source"
]

# Sample dog park data
sample_parks = [
    # Berlin
    {
        "id": 1,
        "name": "Hundeauslaufgebiet Grunewald",
        "address": "Jagen 86, 14193 Berlin",
        "postal_code": "14193",
        "city": "Berlin",
        "state": "Berlin",
        "latitude": "52.4838",
        "longitude": "13.2393",
        "google_maps_url": "https://goo.gl/maps/8ZQJQbP5vZJ2",
        "phone": "",
        "opening_hours": "24/7",
        "website": "https://www.berlin.de/forsten/waldschutz/hundeauslauf/",
        "description": "Großes Hundeauslaufgebiet im Grunewald mit vielen Wegen und Wasserzugang. Ideal für längere Spaziergänge mit dem Hund.",
        "is_fenced": "no",
        "has_water": "yes",
        "has_agility": "no",
        "has_seating": "yes",
        "has_waste_bins": "yes",
        "has_lighting": "no",
        "has_parking": "yes",
        "photos": "",
        "rating": "4.7",
        "reviews": "Toller Wald für Hunde! | Sehr schönes Auslaufgebiet, viel Platz zum Toben | Perfekt für lange Spaziergänge mit dem Hund",
        "size": "large",
        "last_updated": datetime.now().strftime("%Y-%m-%d"),
        "data_source": "Sample Data"
    },
    {
        "id": 2,
        "name": "Hundeplatz Mauerpark",
        "address": "Gleimstraße 55, 10437 Berlin",
        "postal_code": "10437",
        "city": "Berlin",
        "state": "Berlin",
        "latitude": "52.5419",
        "longitude": "13.4022",
        "google_maps_url": "https://goo.gl/maps/vN8YQZ1LXLJ2",
        "phone": "",
        "opening_hours": "Mo-So: 06:00-22:00 Uhr",
        "website": "",
        "description": "Eingezäunter Hundeplatz im beliebten Mauerpark. Besonders am Wochenende sehr gut besucht.",
        "is_fenced": "yes",
        "has_water": "no",
        "has_agility": "no",
        "has_seating": "yes",
        "has_waste_bins": "yes",
        "has_lighting": "yes",
        "has_parking": "no",
        "photos": "",
        "rating": "4.2",
        "reviews": "Guter Platz für Hunde zum Spielen | Manchmal sehr voll, aber die Hunde haben Spaß | Schön eingezäunt, fühlt sich sicher an",
        "size": "medium",
        "last_updated": datetime.now().strftime("%Y-%m-%d"),
        "data_source": "Sample Data"
    },
    {
        "id": 3,
        "name": "Hundefreilaufgebiet Tempelhofer Feld",
        "address": "Tempelhofer Damm, 12101 Berlin",
        "postal_code": "12101",
        "city": "Berlin",
        "state": "Berlin",
        "latitude": "52.4738",
        "longitude": "13.4043",
        "google_maps_url": "https://goo.gl/maps/XyZ123AbC",
        "phone": "",
        "opening_hours": "Sommer: 06:00-22:30 Uhr; Winter: 07:00-20:30 Uhr",
        "website": "https://gruen-berlin.de/tempelhofer-feld",
        "description": "Großzügiges Hundeauslaufgebiet auf dem ehemaligen Flughafen Tempelhof. Viel Platz zum Rennen und Spielen.",
        "is_fenced": "partially",
        "has_water": "no",
        "has_agility": "no",
        "has_seating": "yes",
        "has_waste_bins": "yes",
        "has_lighting": "partial",
        "has_parking": "yes",
        "photos": "",
        "rating": "4.8",
        "reviews": "Perfekt für Hunde, die gerne rennen | Riesige Fläche, ideal für aktive Hunde | Mein Hund liebt es hier",
        "size": "large",
        "last_updated": datetime.now().strftime("%Y-%m-%d"),
        "data_source": "Sample Data"
    },
    
    # Hamburg
    {
        "id": 4,
        "name": "Hundeauslaufzone Stadtpark",
        "address": "Stadtpark, 22303 Hamburg",
        "postal_code": "22303",
        "city": "Hamburg",
        "state": "Hamburg",
        "latitude": "53.5964",
        "longitude": "10.0152",
        "google_maps_url": "https://goo.gl/maps/AbCdEfG123",
        "phone": "",
        "opening_hours": "24/7",
        "website": "https://www.hamburg.de/stadtpark/",
        "description": "Beliebte Hundeauslaufzone im Hamburger Stadtpark mit viel Grünfläche.",
        "is_fenced": "no",
        "has_water": "yes",
        "has_agility": "no",
        "has_seating": "yes",
        "has_waste_bins": "yes",
        "has_lighting": "partial",
        "has_parking": "yes",
        "photos": "",
        "rating": "4.5",
        "reviews": "Schöne große Fläche für Hunde | Viele andere Hunde zum Spielen | Gut gepflegt und sauber",
        "size": "large",
        "last_updated": datetime.now().strftime("%Y-%m-%d"),
        "data_source": "Sample Data"
    },
    {
        "id": 5,
        "name": "Hundeplatz Alstervorland",
        "address": "Schwanenwik, 22087 Hamburg",
        "postal_code": "22087",
        "city": "Hamburg",
        "state": "Hamburg",
        "latitude": "53.5662",
        "longitude": "10.0159",
        "google_maps_url": "https://goo.gl/maps/123XyZAbC",
        "phone": "",
        "opening_hours": "24/7",
        "website": "",
        "description": "Hundeauslaufzone mit Alsterblick. Besonders beliebt bei Hundebesitzern aus der Innenstadt.",
        "is_fenced": "no",
        "has_water": "yes",
        "has_agility": "no",
        "has_seating": "yes",
        "has_waste_bins": "yes",
        "has_lighting": "yes",
        "has_parking": "limited",
        "photos": "",
        "rating": "4.3",
        "reviews": "Tolle Lage an der Alster | Hunde können auch ins Wasser | Manchmal etwas überfüllt am Wochenende",
        "size": "medium",
        "last_updated": datetime.now().strftime("%Y-%m-%d"),
        "data_source": "Sample Data"
    },
    
    # München
    {
        "id": 6,
        "name": "Hundewiese Englischer Garten",
        "address": "Englischer Garten, 80538 München",
        "postal_code": "80538",
        "city": "München",
        "state": "Bayern",
        "latitude": "48.1642",
        "longitude": "11.6057",
        "google_maps_url": "https://goo.gl/maps/AbC123XyZ",
        "phone": "",
        "opening_hours": "24/7",
        "website": "https://www.muenchen.de/freizeit/englischer-garten",
        "description": "Hundewiese im berühmten Englischen Garten. Viel Platz zum Spielen und Toben.",
        "is_fenced": "no",
        "has_water": "yes",
        "has_agility": "no",
        "has_seating": "yes",
        "has_waste_bins": "yes",
        "has_lighting": "partial",
        "has_parking": "yes",
        "photos": "",
        "rating": "4.6",
        "reviews": "Wunderschöne Umgebung für Hundespaziergänge | Mein Hund liebt es hier | Viel Platz zum Rennen",
        "size": "large",
        "last_updated": datetime.now().strftime("%Y-%m-%d"),
        "data_source": "Sample Data"
    },
    {
        "id": 7,
        "name": "Eingezäunte Hundewiese Riemer Park",
        "address": "Riemer Park, 81829 München",
        "postal_code": "81829",
        "city": "München",
        "state": "Bayern",
        "latitude": "48.1308",
        "longitude": "11.7018",
        "google_maps_url": "https://goo.gl/maps/123AbCXyZ",
        "phone": "",
        "opening_hours": "24/7",
        "website": "",
        "description": "Große eingezäunte Hundewiese im Riemer Park. Ideal für Hunde, die sicher spielen sollen.",
        "is_fenced": "yes",
        "has_water": "yes",
        "has_agility": "yes",
        "has_seating": "yes",
        "has_waste_bins": "yes",
        "has_lighting": "no",
        "has_parking": "yes",
        "photos": "",
        "rating": "4.9",
        "reviews": "Perfekt eingezäunt, ideal für unsichere Hunde | Tolle Agility-Geräte | Sehr sauber und gut gepflegt",
        "size": "large",
        "last_updated": datetime.now().strftime("%Y-%m-%d"),
        "data_source": "Sample Data"
    },
    
    # Köln
    {
        "id": 8,
        "name": "Hundespielplatz Stadtwald",
        "address": "Stadtwald, 50935 Köln",
        "postal_code": "50935",
        "city": "Köln",
        "state": "Nordrhein-Westfalen",
        "latitude": "50.9246",
        "longitude": "6.9192",
        "google_maps_url": "https://goo.gl/maps/XyZ123AbC",
        "phone": "",
        "opening_hours": "24/7",
        "website": "",
        "description": "Beliebter Hundespielplatz im Kölner Stadtwald mit verschiedenen Spielgeräten.",
        "is_fenced": "yes",
        "has_water": "yes",
        "has_agility": "yes",
        "has_seating": "yes",
        "has_waste_bins": "yes",
        "has_lighting": "no",
        "has_parking": "yes",
        "photos": "",
        "rating": "4.7",
        "reviews": "Toller Spielplatz für Hunde | Die Agility-Geräte sind super | Mein Hund freut sich immer, wenn wir hierher kommen",
        "size": "medium",
        "last_updated": datetime.now().strftime("%Y-%m-%d"),
        "data_source": "Sample Data"
    },
    {
        "id": 9,
        "name": "Hundefreilauffläche Rheinpark",
        "address": "Rheinpark, 50679 Köln",
        "postal_code": "50679",
        "city": "Köln",
        "state": "Nordrhein-Westfalen",
        "latitude": "50.9472",
        "longitude": "6.9767",
        "google_maps_url": "https://goo.gl/maps/AbC123XyZ",
        "phone": "",
        "opening_hours": "Sommer: 06:00-22:00 Uhr; Winter: 07:00-20:00 Uhr",
        "website": "https://www.koeln.de/freizeit/rheinpark",
        "description": "Hundefreilauffläche mit Rheinblick. Besonders schön bei gutem Wetter.",
        "is_fenced": "partially",
        "has_water": "yes",
        "has_agility": "no",
        "has_seating": "yes",
        "has_waste_bins": "yes",
        "has_lighting": "yes",
        "has_parking": "yes",
        "photos": "",
        "rating": "4.4",
        "reviews": "Schöne Lage am Rhein | Hunde können auch ins Wasser | Gut erreichbar mit öffentlichen Verkehrsmitteln",
        "size": "medium",
        "last_updated": datetime.now().strftime("%Y-%m-%d"),
        "data_source": "Sample Data"
    },
    
    # Dresden
    {
        "id": 10,
        "name": "Hundewiese Großer Garten",
        "address": "Großer Garten, 01069 Dresden",
        "postal_code": "01069",
        "city": "Dresden",
        "state": "Sachsen",
        "latitude": "51.0373",
        "longitude": "13.7644",
        "google_maps_url": "https://goo.gl/maps/123XyZAbC",
        "phone": "",
        "opening_hours": "24/7",
        "website": "",
        "description": "Hundewiese im historischen Großen Garten. Viel Platz zum Spielen in schöner Umgebung.",
        "is_fenced": "no",
        "has_water": "no",
        "has_agility": "no",
        "has_seating": "yes",
        "has_waste_bins": "yes",
        "has_lighting": "partial",
        "has_parking": "yes",
        "photos": "",
        "rating": "4.3",
        "reviews": "Schöne Grünfläche für Hunde | Historische Umgebung | Gut erreichbar",
        "size": "medium",
        "last_updated": datetime.now().strftime("%Y-%m-%d"),
        "data_source": "Sample Data"
    },
    
    # Frankfurt
    {
        "id": 11,
        "name": "Hundeauslaufgebiet Niddapark",
        "address": "Niddapark, 60439 Frankfurt",
        "postal_code": "60439",
        "city": "Frankfurt",
        "state": "Hessen",
        "latitude": "50.1477",
        "longitude": "8.6363",
        "google_maps_url": "https://goo.gl/maps/AbCXyZ123",
        "phone": "",
        "opening_hours": "24/7",
        "website": "https://www.frankfurt.de/niddapark",
        "description": "Großes Hundeauslaufgebiet im Niddapark mit Wasserzugang. Ideal für aktive Hunde.",
        "is_fenced": "partially",
        "has_water": "yes",
        "has_agility": "no",
        "has_seating": "yes",
        "has_waste_bins": "yes",
        "has_lighting": "no",
        "has_parking": "yes",
        "photos": "",
        "rating": "4.5",
        "reviews": "Tolles Gebiet zum Laufen | Mein Hund liebt das Wasser hier | Viel Platz zum Spielen mit anderen Hunden",
        "size": "large",
        "last_updated": datetime.now().strftime("%Y-%m-%d"),
        "data_source": "Sample Data"
    },
    
    # Hannover
    {
        "id": 12,
        "name": "Hundewiese Eilenriede",
        "address": "Eilenriede, 30161 Hannover",
        "postal_code": "30161",
        "city": "Hannover",
        "state": "Niedersachsen",
        "latitude": "52.3844",
        "longitude": "9.7731",
        "google_maps_url": "https://goo.gl/maps/123AbCXyZ",
        "phone": "",
        "opening_hours": "24/7",
        "website": "",
        "description": "Hundewiese im größten Stadtwald Europas. Viele Wege und Flächen für Hunde.",
        "is_fenced": "no",
        "has_water": "yes",
        "has_agility": "no",
        "has_seating": "yes",
        "has_waste_bins": "yes",
        "has_lighting": "partial",
        "has_parking": "yes",
        "photos": "",
        "rating": "4.6",
        "reviews": "Wunderschöner Wald für Hundespaziergänge | Viele Wege zum Erkunden | Gut gepflegt",
        "size": "large",
        "last_updated": datetime.now().strftime("%Y-%m-%d"),
        "data_source": "Sample Data"
    },
    
    # Indoor dog parks
    {
        "id": 13,
        "name": "Hunde Indoor Spielplatz Berlin",
        "address": "Industriestraße 85, 13088 Berlin",
        "postal_code": "13088",
        "city": "Berlin",
        "state": "Berlin",
        "latitude": "52.5558",
        "longitude": "13.4242",
        "google_maps_url": "https://goo.gl/maps/AbC123XyZ",
        "phone": "+49 30 12345678",
        "opening_hours": "Mo-Fr: 10:00-19:00 Uhr; Sa-So: 10:00-18:00 Uhr",
        "website": "https://hunde-indoor-berlin.de",
        "description": "Indoor Hundespielplatz für alle Wetterlagen. Mit verschiedenen Spielgeräten und Agility-Parcours.",
        "is_fenced": "yes",
        "has_water": "yes",
        "has_agility": "yes",
        "has_seating": "yes",
        "has_waste_bins": "yes",
        "has_lighting": "yes",
        "has_parking": "yes",
        "photos": "",
        "rating": "4.8",
        "reviews": "Perfekt für Regentage | Tolle Ausstattung | Freundliches Personal und saubere Anlage",
        "size": "medium",
        "last_updated": datetime.now().strftime("%Y-%m-%d"),
        "data_source": "Sample Data"
    },
    {
        "id": 14,
        "name": "Doggy Hall München",
        "address": "Gewerbestraße 12, 80939 München",
        "postal_code": "80939",
        "city": "München",
        "state": "Bayern",
        "latitude": "48.1895",
        "longitude": "11.5786",
        "google_maps_url": "https://goo.gl/maps/XyZ123AbC",
        "phone": "+49 89 87654321",
        "opening_hours": "Mo-Fr: 09:00-20:00 Uhr; Sa-So: 10:00-18:00 Uhr",
        "website": "https://doggy-hall.de",
        "description": "Große Indoor-Spielfläche für Hunde mit Agility-Parcours und Trainingsangeboten.",
        "is_fenced": "yes",
        "has_water": "yes",
        "has_agility": "yes",
        "has_seating": "yes",
        "has_waste_bins": "yes",
        "has_lighting": "yes",
        "has_parking": "yes",
        "photos": "",
        "rating": "4.7",
        "reviews": "Super Konzept | Mein Hund liebt es hier | Gute Trainingsmöglichkeiten",
        "size": "large",
        "last_updat
(Content truncated due to size limit. Use line ranges to read in chunks)